a = input('Digite algo: ')
print('O tipo primitivo é', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número ?', a.isnumeric())
print('É um alfabético?', a.isalpha())
print('É um alfanumérico?', a.isalnum())
print('Está em maiúsvulas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('Esta capitalizada?', a.istitle())
